# bump-version.ps1
# Stamps a new version into frontend/src/version.js using format yy.MM.dd.HHmm
# Usage: .\bump-version.ps1
#        .\bump-version.ps1 -Commit   (also does git add + commit)

param(
    [switch]$Commit
)

$v    = (Get-Date).ToString("yy.MM.dd.HHmm")
$file = Join-Path $PSScriptRoot "frontend\src\version.js"

$content = @"
// Auto-generated by bump-version.ps1 — do not edit manually
export const VERSION = '$v';
"@

Set-Content -Path $file -Value $content -Encoding UTF8
Write-Host "Version bumped to $v" -ForegroundColor Green

if ($Commit) {
    Set-Location $PSScriptRoot
    git add frontend/src/version.js
    git commit -m "chore: bump version to $v"
    Write-Host "Committed." -ForegroundColor Cyan
}
